kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: myfirstk8scluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  - containerPort: 80
    hostPort: 8080
    protocol: TCP



